name: Godot testing

on: [ push ]

jobs:
  execute-gut:
    name: Run GUT Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Unit Test
      uses: ceceppa/godot-gut-ci@main
      with:
        godot_version: 4.3
        gut_params: -gdir=res://tests -gprefix=test_ -gsuffix=
        project_path: godot-project
        